add form and styles
FSBurn/Todo_React pull request #2
Opened 2022-08-15 16:54 UTC by FSBurn

2022-08-16 13:47 UTC, Limonades requested changes
В карточках должен выводится текст, который ты ввел в инпут. И плюс еще компоненты - нужно сделать их отдельными.

2022-08-16 13:47 UTC, Limonades commented on src/Components/Todo.jsx
> +                title: "event.target.value",
Нужно убрать кавычки

2022-08-16 13:47 UTC, Limonades commented on src/Components/Todo.jsx
> +        event.preventDefault()
Обычно размещается внчале функции

2022-08-16 13:47 UTC, Limonades commented on src/Components/Todo.jsx
>          setCards(cards.filter((element, index) => index < cards.length - 1))
Этот метод удаляет последний элемент, а должен удаляться текущий

2022-08-16 13:47 UTC, Limonades commented on src/Components/Todo.jsx
> +                key={index}>Task: {index + 1}
Не рекомендуется использовать индекс в качестве ключа. Тем более если у тебя есть id

https://sacret.medium.com/%D0%B8%D0%BD%D0%B4%D0%B5%D0%BA%D1%81-%D0%B2-%D0%BA%D0%B0%D1%87%D0%B5%D1%81%D1%82%D0%B2%D0%B5-%D0%BA%D0%BB%D1%8E%D1%87%D0%B0-%D0%B0%D0%BD%D1%82%D0%B8-%D0%BF%D0%B0%D1%82%D1%82%D0%B5%D1%80%D0%BD-56bab8ada309

2022-08-16 13:47 UTC, Limonades commented on src/Components/Todo.jsx
> +                <button className={"card_button"} onClick={removeCard}>X
Это не ошибка, но просто проговорю. Если в атрибуте нет js то не обязательно использовать фигурные скобки. className={"card_button"} === className="card_button"

2022-08-19 09:24 UTC, Vladyslav-Kryvokon requested changes

2022-08-19 09:24 UTC, Vladyslav-Kryvokon commented on src/App.css
> +}
You can remove all styles and files related to react default template

2022-08-19 09:24 UTC, Vladyslav-Kryvokon commented on src/Components/Todo/Todo.jsx
> +                title: newCardTitle.title,
Рабочий вариант, но чуть излишне. Значение инпута можно извлеч из обьекта event. Тем самым убрать дополнительный метод changeCard и обьект

2022-08-19 09:24 UTC, Vladyslav-Kryvokon commented on src/Components/Todo/Todo.jsx
> +                <TodoHeader cards={cards}/>
Имеет смысл сюда просто передать длину массива cards

2022-08-19 09:24 UTC, Vladyslav-Kryvokon commented on src/Components/Todo/TodoCard/TodoCard.jsx
> +export default function TodoCard(props) {
На будущее. Очень удобная штука деструктуризация. TodoCard(props) ---> TodoCard({ cards })
И ниже в коде уже можно не писать "props." а напрямую обращаться к названиям пропсов, в данном случае это cards. 

Если пропсов несколько, то они указываются в аргументе через запятую TodoCard({ cards, hello, world })

2022-08-19 09:24 UTC, Vladyslav-Kryvokon commented on src/Components/Todo/TodoSubmit/TodoSubmit.jsx
> +        <form onSubmit={props.addCard} className={styles.todoItem}>
Есть пару багов по сабмиту. 
1. Если ввести название и нажать сабмит. То текст не очищается. Должен очищаться в инпуте.
2. Если нажать на сабмит с предыдущим текстом, то создается пустая карточка, без тайтла. 

Приступай к этому после того как переделаешь логику добавления карточки (удалить changeCard). Возможно 2й баг сам по себе уйдет

2022-08-19 09:24 UTC, Vladyslav-Kryvokon commented on src/Components/Todo/TodoSubmit/TodoSubmit.jsx
> +                <input  onChange={props.changeCard}
https://reactjs.org/docs/forms.html#controlled-components

Тут описано как нужно работать с инпутами в реакте. А именно отвечать с велью через стейт компонента.

2022-08-19 09:27 UTC, Vladyslav-Kryvokon commented on src/Components/Todo/TodoSubmit/TodoSubmit.jsx
> +                <input  onChange={props.changeCard}
Понадобится при очещении инпута

2022-08-23 18:24 UTC, Vladyslav-Kryvokon approved these changes

2022-08-23 18:25 UTC, Limonades approved these changes

2022-08-23 18:25 UTC, Limonades commented on src/Components/Todo/TodoCard/TodoCard.jsx
> +        <div>{props.cards.length ? props.cards.map((newDiv) => <div
newDiv лучше будет назвать card

2022-08-24 02:49 UTC, merged